server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.mall.demo.model
  mapper-locations: classpath*:/mapping/PmsBrandMapper.xml
#  mapper-locations: classpath*:/mapping/*.xml
